const animeDatabase = [
    // --- SEZIONE PRINCIPALE ---
    { title: "Love chunibyo & other delusions", img: "img/Love chunibyo & other delusions.jpg", section: "principale" },
    { title: "Dr.stone", img: "img/Dr stone.jpg", section: "principale" },
    { title: "Bungo Stray Dogs", img: "img/Bungo Stray Dogs.jpg", section: "principale" },
    { title: "Code Geass: Lelouch of the Rebellion", img: "https://myanimelist.net/images/anime/1088/135089.jpg", section: "principale" },
    { title: "Death note", img: "img/Death note.jpg", section: "principale" },
    { title: "A Certain Scientific Railgun", img: "img/A Certain Scientific Railgun.jpg", section: "principale" },
    { title: "Demon slayer", img: "img/Demon slayer.jpg", section: "principale" },
    { title: "Elite classroom", img: "img/Elite classroom.jpg", section: "principale" },
    { title: "Re:Zero - Starting Life in Another World", img: "img/Re_Zero - Starting Life in Another World.jpg", section: "principale" },
    { title: "Overlord", img: "img/overlord.jpg", section: "principale" },
    { title: "Jujutsu kaisen", img: "img/Jujutsu kaisen.jpg", section: "principale" },
    { title: "One punch man", img: "img/One punch man.jpg", section: "principale" },
    { title: "Frieren - Oltre la fine del viaggio", img: "img/Frieren - Oltre la fine del viaggio.jpg", section: "principale" },
    { title: "Solo leveling", img: "img/Solo leveling.jpg", section: "principale" },
    { title: "My deer friend nokotan", img: "img/my deer friend nokotan.jpg", section: "principale" },
    { title: "Nukitashi", img: "img/Nukitashi.jpg", section: "principale" },
    { title: "Egumi legacy", img: "img/Egumi legacy.jpg", section: "principale" },
    { title: "Angels of Death", img: "img/Angels of Death.jpg", section: "principale" },
    { title: "The Promised Neverland", img: "img/The Promised Neverland.jpg", section: "principale" },
    { title: "Mashle: Magic And Muscles", img: "img/Mashle_Magic And Muscles.jpg", section: "principale" },
    { title: "Orb: On the Movements of the Earth", img: "img/Orb_On the Movements of the Earth.jpg", section: "principale" },
    { title: "Goblin Slayer", img: "img/Goblin Slayer.jpg", section: "principale" },
    { title: "A Certain Magical Index", img: "img/A Certain Magical Index.jpg", section: "principale" },
    { title: "A certain scientific accelerator", img: "img/a certain scientific accelerator.jpg", section: "principale" },
    { title: "Alya Sometimes Hides Her Feelings in Russian", img: "img/Alya Sometimes Hides Her Feelings in Russian.jpg", section: "principale" },

    // --- OTTOBRE 2025 - MARZO 2026 ---
    { title: "Neon Genesis Evangelion", img: "img/Neon Genesis Evangelion.jpg", section: "ott25-mar26" },
    { title: "Steins;Gate", img: "img/Steins;Gate.jpg", section: "ott25-mar26" },
    { title: "Bocchi The rock", img: "img/Bocchi The rock.jpg", section: "ott25-mar26" },
    { title: "Spy family", img: "img/Spy family.jpg", section: "ott25-mar26" },
    { title: "Fullmetal alchemist", img: "img/Fullmetal alchemist.jpg", section: "ott25-mar26" },
    { title: "It's mygo", img: "img/it's mygo.jpg", section: "ott25-mar26" },
    { title: "Ave mujica", img: "https://cdn.myanimelist.net/images/anime/1181/148235.jpg", section: "ott25-mar26" },
    { title: "Your lie in April", img: "img/your-lie-in-april.jpg", section: "ott25-mar26" },
    { title: "Your name", img: "img/Your-name.jpg", section: "ott25-mar26" },
    { title: "Clannad", img: "img/clannad.jpg", section: "ott25-mar26" },
    { title: "Kaguya sama:love is war", img: "img/kaguya-sama-love-is-war.jpg", section: "ott25-mar26" },
    { title: "The quintessential quintuplets", img: "img/the quintessential quintuplets.jpg", section: "ott25-mar26" },
    { title: "Rascal Does Not Dream of Bunny Girl Senpai", img: "https://cdn.myanimelist.net/images/anime/1301/93586.jpg", section: "ott25-mar26" },
    { title: "Madoka magica", img: "img/madoka magica.jpg", section: "ott25-mar26" },
    { title: "Oshi no ko", img: "img/oshinoko.jpg", section: "ott25-mar26" },
    { title: "Ano hana", img: "img/anohana.jpg", section: "ott25-mar26" },
    { title: "Revue☆Starlight", img: "img/Revue_Starlight.png", section: "ott25-mar26" },
    { title: "Uma Musume:Pretty Derby", img: "img/UmaMusume_PrettyDerby.jpeg", section: "ott25-mar26" },
    { title: "Uma Musume:Pretty Derby 2", img: "https://myanimelist.net/images/anime/1447/114282.jpg", section: "ott25-mar26" },
    { title: "Uma Musume:Pretty Derby 3", img: "https://myanimelist.net/images/anime/1475/138948.jpg", section: "ott25-mar26" },
    { title: "Uma Musume:Pretty Derby - Road to the Top", img: "https://myanimelist.net/images/anime/1421/142243.jpg", section: "ott25-mar26" },
    { title: "Uma Musume:Pretty Derby - Beginning of a New Era", img: "https://myanimelist.net/images/anime/1427/142210.jpg", section: "ott25-mar26" },
    { title: "Uma Musume: Cinderella Gray", img: "https://myanimelist.net/images/anime/1626/148097.jpg", section: "ott25-mar26" },
    { title: "5 Centimeters per Second", img: "https://myanimelist.net/images/anime/1410/112994.jpg", section: "ott25-mar26" },
    { title: "I Want to Eat Your Pancreas", img: "img/I Want to Eat Your Pancreas.jpeg", section: "ott25-mar26" },

    // --- APRILE 2026 - SETTEMBRE 2026 ---
    { title: "Violet evergarden", img: "img/violet evergarden.jpg", section: "apr26-set26" },
    { title: "K-On", img: "https://myanimelist.net/images/anime/10/76120.jpg", section: "apr26-set26" },
    { title: "Botan Kamiina Fully Blossoms When Drunk", img: "https://myanimelist.net/images/anime/1026/155965.jpg", section: "apr26-set26" },
    { title: "You and I Are Polar Opposites", img: "https://myanimelist.net/images/anime/1140/154457.jpg", section: "apr26-set26" },
    { title: "The Ramparts of Ice", img: "https://myanimelist.net/images/anime/1565/154933.jpg", section: "apr26-set26" },
    { title: "Erased", img: "https://myanimelist.net/images/anime/10/77957.jpg", section: "apr26-set26" },
    { title: "Witch Hat Atelier", img: "https://myanimelist.net/images/anime/1726/155542.jpg", section: "apr26-set26" },
    { title: "Teasing Master Takagi-san", img: "https://myanimelist.net/images/anime/1591/95091.jpg", section: "apr26-set26" },
    { title: "The Melancholy of Haruhi Suzumiya", img: "https://myanimelist.net/images/anime/1470/137929.jpg", section: "apr26-set26" },
    { title: "Smoking Behind the Supermarket with You", img: "https://cdn.myanimelist.net/images/anime/1768/156339.jpg", section: "apr26-set26" },
    { title: "Mushoku Tensei", img: "https://cdn.myanimelist.net/images/anime/1530/117776.jpg", section: "apr26-set26" },    
    { title: "I Want to Love You Till Your Dying Day", img: "https://cdn.myanimelist.net/images/anime/1096/158712.jpg", section: "apr26-set26" },
    { title: "Love Unseen Beneath the Clear Night Sky", img: "https://cdn.myanimelist.net/images/anime/1145/158339.jpg", section: "apr26-set26" },
    { title: "Yani Neko", img: "https://cdn.myanimelist.net/images/anime/1281/156496.jpg", section: "apr26-set26" },
    { title: "BanG Dream! Yume∞Mita", img: "https://cdn.myanimelist.net/images/anime/1467/158693.jpg", section: "apr26-set26" },
    { title: "The Klutzy Class Monitor and the Girl with the Short Skirt", img: "https://cdn.myanimelist.net/images/anime/1484/155726.jpg", section: "apr26-set26" },
    { title: "The Dangers in My Heart", img: "https://cdn.myanimelist.net/images/anime/1545/133887.jpg", section: "apr26-set26" },
    { title: "Sakamoto desu ga?", img: "https://cdn.myanimelist.net/images/anime/4/79468.jpg", section: "apr26-set26" },

    // --- ANIME IN LISTA ---
    { title: "Made in abyss", img: "img/made in abyss.jpg", section: "in-lista" },
    { title: "Saekano: How to Raise a Boring Girlfriend", img: "img/Saekano How to Raise a Boring Girlfriend.jpeg", section: "in-lista" },
    { title: "My Teen Romance Comedy: SNAFU", img: "img/My Teen Romance Comedy SNAFU.jpeg", section: "in-lista" },
    { title: "Oreimo - My Sister Can't Be This Cute", img: "img/Oreimo - My Sister Can't Be This Cute.jpeg", section: "in-lista" },
    { title: "TONIKAWA: Over The Moon For You", img: "img/TONIKAWA Over The Moon For You.jpeg", section: "in-lista" },
    { title: "Attack on titan", img: "img/attack on titan.jpg", section: "in-lista" },
    { title: "Wataten! an Angel Flew Down to Me", img: "https://myanimelist.net/images/anime/1778/100470.jpg", section: "in-lista" },
    { title: "Suzume", img: "https://myanimelist.net/images/anime/1598/128450.jpg", section: "in-lista" },
    { title: "Weathering with You", img: "https://myanimelist.net/images/anime/1880/101146.jpg", section: "in-lista" },
    { title: "Cosmic Princess Kaguya!", img: "https://myanimelist.net/images/anime/1758/153953.jpg", section: "in-lista" },
    { title: "Summer Time Rendering", img: "https://myanimelist.net/images/anime/1120/120796.jpg", section: "in-lista" },
    { title: "Date A Live", img: "https://myanimelist.net/images/anime/13/44844.jpg", section: "in-lista" },
    { title: "Makeine: Too Many Losing Heroines!", img: "https://myanimelist.net/images/anime/1332/143513.jpg", section: "apr26-set26" },
    { title: "KonoSuba: God's Blessing on This Wonderful World!", img: "https://myanimelist.net/images/anime/1895/142748.jpg", section: "in-lista" },
    { title: "Air", img: "https://myanimelist.net/images/anime/8/73522.jpg", section: "in-lista" },
    { title: "Charlotte", img: "https://myanimelist.net/images/anime/1826/147276.jpg", section: "in-lista" },
    { title: "Nichijou", img: "https://myanimelist.net/images/anime/3/75617.jpg", section: "apr26-set26" },
    { title: "Grand Blue", img: "https://myanimelist.net/images/anime/1302/94882.jpg", section: "in-lista" }
];